# This docker-compose configuration is for ICMS development and CI environment.
# Production deployment does not use this configuration.
version: "3"
services:
    db:
        image: postgres:11
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"

    web:
        build:
            context: .
        entrypoint: dockerize -wait tcp://db:5432 -timeout 20s
        command: scripts/entry.sh
        environment:
            - PYTHONUNBUFFERED=1
            - ICMS_WEB_PORT
            - ICMS_DEBUG
            - ICMS_NUM_WORKERS # Gunicorn workers number
            - ICMS_MIGRATE
            - ICMS_ADDRESS_API_KEY # getAddress.io api key for post code search
            - COMPANIES_HOUSE_TOKEN # https://developer.company-information.service.gov.uk/api/docs/
            # DATABASE_URL not namespaced due to GOV PaaS setting DATABASE_URL env var
            - DATABASE_URL
            - ICMS_ALLOWED_HOSTS
            - ICMS_RECAPTCHA_PUBLIC_KEY
            - ICMS_RECAPTCHA_PRIVATE_KEY
            - ICMS_SILENCED_SYSTEM_CHECKS
            - ICMS_SECRET_KEY
            - ICMS_EMAIL_FROM
            - AWS_SES_ACCESS_KEY_ID
            - AWS_SES_SECRET_ACCESS_KEY
            - DJANGO_SETTINGS_MODULE
            - ELASTIC_APM_SECRET_TOKEN
            - ELASTIC_APM_ENVIRONMENT
            - ELASTIC_APM_URL
            - DISABLE_DEBUG_TOOLBAR
            - CLAM_AV_USERNAME
            - CLAM_AV_PASSWORD
            - CLAM_AV_URL
        ports:
            - "${ICMS_WEB_PORT}:${ICMS_WEB_PORT}"
        depends_on:
            - db
            - redis
        stdin_open: true
        tty: true
        volumes:
            - ./test-reports:/code/test-reports # needed for ci
            - .:/code

    redis:
        image: redis:latest
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"

    celery:
        build:
            context: .
        command: celery --app=config.celery:app --loglevel=debug worker
        environment:
            - DJANGO_SETTINGS_MODULE
            - AWS_SES_ACCESS_KEY_ID
            - AWS_SES_SECRET_ACCESS_KEY
        depends_on:
            - redis
        volumes:
            - .:/code

    localstack:
        image: localstack/localstack
        ports:
            - "4567-4599:4567-4599"
            - "8081:8080"
        environment:
            - SERVICES=s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - ls_data:/tmp/localstack
            - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
    pgdata:
    ls_data:
    redis_data:
