# Generated by Django 2.2.13 on 2020-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_auto_20200730_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="importer",
            name="eori_number_ni",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
