# Generated by Django 3.1.1 on 2020-09-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_auto_20200911_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportapplication",
            name="case_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_export_applications",
                to="web.user",
            ),
        ),
    ]
