# Generated by Django 3.1.1 on 2020-09-28 12:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_exportapplication_case_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(name="casenote", options={"ordering": ["-create_datetime"]},),
        migrations.AlterModelOptions(name="file", options={"ordering": ["-created_datetime"]},),
        migrations.AlterModelManagers(
            name="file", managers=[("active", django.db.models.manager.Manager()),],
        ),
        migrations.AlterField(
            model_name="casenote",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
