# Generated by Django 3.1.5 on 2021-02-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_verifiedcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionsAndAdhocApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                ("section1", models.BooleanField(default=True, verbose_name="Section 1")),
            ],
            bases=("web.importapplication",),
        ),
    ]
