# Generated by Django 3.1.5 on 2021-02-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_sanctionsandadhocapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanctionsandadhocapplication",
            name="section1",
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="sub_type",
            field=models.CharField(
                blank=True,
                choices=[("OIL", "Open Individual Import Licence"), ("SA", "Sanctions and Adhoc")],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[("FA", "Firearms and Ammunition"), ("SA", "Sanctions and Adhoc")],
                max_length=70,
            ),
        ),
    ]
