# Generated by Django 3.1.5 on 2021-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_add_case_reference_template"),
        ("web", "0021_auto_20210211_1125"),
    ]

    operations = []
