# Generated by Django 3.1.5 on 2021-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_checklistfirearmsoilapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name", "is_active")},
        ),
        migrations.AlterField(
            model_name="countrygroup",
            name="name",
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name="countrygroup",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
