# Generated by Django 3.1.5 on 2021-03-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0042_sanctionsdocument"),
        ("web", "0046_add_derogations_fields"),
    ]

    operations = []
