# Generated by Django 3.1.5 on 2021-03-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_sanctionsandadhocapplication_supporting_documents"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SanctionsDocument",
        ),
    ]
